USE [master]
GO

CREATE DATABASE [test]
--CONTAINMENT = PARTIAL
ON  PRIMARY 
( NAME = N'test', FILENAME = N'C:\var\opt\mssql\data\test.mdf' , SIZE = 3682560KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20480KB )
LOG ON 
( NAME = N'test_log', FILENAME = N'C:\var\opt\mssql\data\test_log.ldf' , SIZE = 69760KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

/* For security reasons the login is created disabled and with a random password. */
/****** Object:  Login [test]    Script Date: 05.02.2017 16:52:19 ******/
CREATE LOGIN [test] WITH PASSWORD=N'XXXXXXXXXXXXXXXXXXXX', DEFAULT_DATABASE=[test], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [test] ENABLE
GO


USE [test]
GO
CREATE TABLE [dbo].[hashes](
	[key] [varchar](20) NOT NULL,
	[hashMD5] [char](32) NOT NULL,
	[hashSHA256] [char](64) NOT NULL,
 CONSTRAINT [PK_KEY_PRIMARY] PRIMARY KEY CLUSTERED 
(
	[key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_MD5]    Script Date: 05.02.2017 12:17:01 ******/
CREATE NONCLUSTERED INDEX [IX_MD5] ON [dbo].[hashes]
(
	[hashMD5] ASC
)
INCLUDE ([hashSHA256]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_SHA256]    Script Date: 05.02.2017 12:17:14 ******/
CREATE NONCLUSTERED INDEX [IX_SHA256] ON [dbo].[hashes]
(
	[hashSHA256] ASC
)
INCLUDE ([hashMD5]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
--ALTER INDEX [PK_KEY_PRIMARY] ON [dbo].[hashes] DISABLE
GO
ALTER INDEX [IX_MD5] ON [dbo].[hashes] DISABLE
GO
ALTER INDEX [IX_SHA256] ON [dbo].[hashes] DISABLE
GO

CREATE USER [test] FOR LOGIN [test] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [test]
GO
